fix another compilation error on 8.1 due to missing header
hardware/qcom/media-caf/msm8916/libstagefrighthw/QComOMXMetadata.h:21:10: fatal error: 'system/window.h' file not found
* etc